# Generated by Django 4.2.16 on 2024-10-25 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyweathersummary',
            options={'verbose_name_plural': 'daily weather summaries'},
        ),
        migrations.AlterModelOptions(
            name='weatherdata',
            options={},
        ),
        migrations.RenameField(
            model_name='weatheralert',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dailyweathersummary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weatheralert',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='dailyweathersummary',
            name='condition_distribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dailyweathersummary',
            name='sample_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='current_value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='threshold',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyweathersummary',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='alert_type',
            field=models.CharField(choices=[('high_temp', 'High Temperature'), ('extreme_weather', 'Extreme Weather')], max_length=50),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_temp_threshold', models.FloatField(default=35.0)),
                ('consecutive_checks', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
            ],
        ),
    ]
