# Generated by Django 4.2.16 on 2024-10-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_dailyweathersummary_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatheralert',
            name='city',
        ),
        migrations.DeleteModel(
            name='AlertConfiguration',
        ),
        migrations.DeleteModel(
            name='WeatherAlert',
        ),
    ]
